### PR TITLE
Add 'stream' and 'interactive' parameter to Tabular

### PR DESCRIPTION
**Pull request by kyleam**
Let callers specify alternative stream and override the `isatty()` decision.

### CODE REVIEW

**Comment by yarikoptic** [comment]
FWIW - looks good to me.

**Comment by kyleam** [comment]
> FWIW - looks good to me.

Thanks for having a look.  I guess the main decision from a user-facing perspective is how to name the parameters.  `stream` seems like the obvious choice to me.  For `interactive`, I also considered `force_styling` (to match the blessings analog) and `isatty`.

**Comment by yarikoptic** [comment]
Related, I went back and forth on either to raise a question, either the .mode of Writer, which is now set by a hardcoded logic depending on the steamer features, should be an explicit argument  (with current logic as a fallback if None). I thought that mode might be something to instruct/force by the user.

Re stream, which implies one directional flow for me, if it is without updates, makes sense. But with all the updates, not sure. But I don't see a better name.

interactive - I don't like force_styling since it is more than that. And we might like to force style even when non interactive. isatty is too specific. It is more of "updatable" (find a better English word), isn't it?

**Comment by kyleam** [comment]
> either the .mode of Writer, which is now set by a hardcoded logic depending on the steamer features, should be an explicit argument (with current logic as a fallback if None). I thought that mode might be something to instruct/force by the user.

The user can set it explicitly with the `.mode` property.  For now I don't feel the need to expose it as an `__init__` parameter.

> Re stream, which implies one directional flow for me, if it is without updates, makes sense. But with all the updates, not sure.

I don't feel the same.  It's a stream, regardless of whether it understands specific update codes.

> interactive - I don't like force_styling since it is more than that. And we might like to force style even when non interactive. isatty is too specific. 

Similar thinking led me to `interactive`.

> It is more of "updatable" (find a better English word), isn't it?

No, it is not a direct map to "updatable".  `interactive` is consulted when setting the default value for `mode` (current "update", "incremental", or "final").  You can be in the "final" mode but still see colors if `interactive` is True.

**Pull request merged**
