### PR TITLE
BF: Raise StyleFunctionError with original traceback

### LINKED ISSUE #43: my neck hurts from "See[ing] above"
Thought to give a shot at a script sketch so there is no datalad needed/involved but failed with our favorite exception and this time there were no 'above' exception listing:
```shell
$> echo '{"a":1, "b": true, "c": null}'| PYTHONPATH=$PWD/.. ./color_json.py
Traceback (most recent call last):
  File "./color_json.py", line 26, in <module>
    out(line_json)
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 549, in __call__
    self._maybe_write_header()
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 398, in _maybe_write_header
    adopt=False, repaint=False)
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 367, in _check_and_write
    self._set_widths(row, proc_group)
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 278, in _set_widths
    exclude_post=True)
  File "/home/yoh/proj/repronim/pyout/pyout/field.py", line 144, in __call__
    result = fn(value, result)
  File "/home/yoh/proj/repronim/pyout/pyout/field.py", line 268, in transform_fn
    raise StyleFunctionError(function)
pyout.field.StyleFunctionError: Style transform <method 'upper' of 'str' objects> raised an exception. See above.
```

### PR DESCRIPTION
**Pull request by kyleam**
We can't rely on the the transform function's error being shown in the
traceback "above" because this depends on the caller's handling of the
StyleFunctionError.  Reraise with the original traceback to ensure
that the original error is present.

Closes #43.

---

### Before

```python
from pyout import Tabular
from humanize import naturalsize

out = Tabular(columns=["name", "size"],
              style={"size": {"transform": naturalsize}})
out({"name": "y", "size": "err"})
```

would show

```
Traceback (most recent call last):
  File "/home/kyle/src/python/pyout/pyout/field.py", line 266, in transform_fn
    return function(result)
  File "/home/kyle/src/python/pyout/venv-pyout/lib/python3.5/site-packages/humanize/filesize.py", line 25, in naturalsize
    bytes = float(value)
ValueError: could not convert string to float: 'err'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_error.py", line 6, in <module>
    out({"name": "y", "size": "err"})
  File "/home/kyle/src/python/pyout/pyout/tabular.py", line 550, in __call__
    self._check_and_write(row, style)
  File "/home/kyle/src/python/pyout/pyout/tabular.py", line 367, in _check_and_write
    self._set_widths(row, proc_group)
  File "/home/kyle/src/python/pyout/pyout/tabular.py", line 278, in _set_widths
    exclude_post=True)
  File "/home/kyle/src/python/pyout/pyout/field.py", line 144, in __call__
    result = fn(value, result)
  File "/home/kyle/src/python/pyout/pyout/field.py", line 268, in transform_fn
    raise StyleFunctionError(function)
pyout.field.StyleFunctionError: Style transform <function naturalsize at 0x7f2aa56e6f28> raised an exception. See above.
```

However, depending on how the caller handled the exception, you could
lose the original traceback.  For example,

```
import sys
import traceback

from pyout import Tabular
from humanize import naturalsize

out = Tabular(columns=["name", "size"],
              style={"size": {"transform": naturalsize}})

try:
    out({"name": "y", "size": "err"})
except:
    entries = traceback.extract_tb(sys.exc_info()[2])
    for entry in entries:
        print("Line {} in {} ({})".format(entry[1], entry[0], entry[2]))
        print("  " + entry[3])
```

```
Line 11 in transform_error_gobble.py (<module>)
  out({"name": "y", "size": "err"})
Line 550 in /home/kyle/src/python/pyout/pyout/tabular.py (__call__)
  self._check_and_write(row, style)
Line 367 in /home/kyle/src/python/pyout/pyout/tabular.py (_check_and_write)
  self._set_widths(row, proc_group)
Line 278 in /home/kyle/src/python/pyout/pyout/tabular.py (_set_widths)
  exclude_post=True)
Line 144 in /home/kyle/src/python/pyout/pyout/field.py (__call__)
  result = fn(value, result)
Line 268 in /home/kyle/src/python/pyout/pyout/field.py (transform_fn)
  raise StyleFunctionError(function)
```

### Now

With the PR, the two output blocks from above (in order) look like

```
Traceback (most recent call last):
  File "transform_error.py", line 6, in <module>
    out({"name": "y", "size": "err"})
  File "/home/kyle/src/python/pyout/pyout/tabular.py", line 550, in __call__
    self._check_and_write(row, style)
  File "/home/kyle/src/python/pyout/pyout/tabular.py", line 367, in _check_and_write
    self._set_widths(row, proc_group)
  File "/home/kyle/src/python/pyout/pyout/tabular.py", line 278, in _set_widths
    exclude_post=True)
  File "/home/kyle/src/python/pyout/pyout/field.py", line 147, in __call__
    result = fn(value, result)
  File "/home/kyle/src/python/pyout/pyout/field.py", line 276, in transform_fn
    six.reraise(StyleFunctionError, new_exc, tb)
  File "/home/kyle/src/python/pyout/venv-pyout/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kyle/src/python/pyout/pyout/field.py", line 268, in transform_fn
    return function(result)
  File "/home/kyle/src/python/pyout/venv-pyout/lib/python3.5/site-packages/humanize/filesize.py", line 25, in naturalsize
    bytes = float(value)
pyout.field.StyleFunctionError: ValueError
  could not convert string to float: 'err'
```

and

```
Line 11 in transform_error_gobble.py (<module>)
  out({"name": "y", "size": "err"})
Line 550 in /home/kyle/src/python/pyout/pyout/tabular.py (__call__)
  self._check_and_write(row, style)
Line 367 in /home/kyle/src/python/pyout/pyout/tabular.py (_check_and_write)
  self._set_widths(row, proc_group)
Line 278 in /home/kyle/src/python/pyout/pyout/tabular.py (_set_widths)
  exclude_post=True)
Line 147 in /home/kyle/src/python/pyout/pyout/field.py (__call__)
  result = fn(value, result)
Line 276 in /home/kyle/src/python/pyout/pyout/field.py (transform_fn)
  six.reraise(StyleFunctionError, new_exc, tb)
Line 692 in /home/kyle/src/python/pyout/venv-pyout/lib/python3.5/site-packages/six.py (reraise)
  raise value.with_traceback(tb)
Line 268 in /home/kyle/src/python/pyout/pyout/field.py (transform_fn)
  return function(result)
Line 25 in /home/kyle/src/python/pyout/venv-pyout/lib/python3.5/site-packages/humanize/filesize.py (naturalsize)
  bytes = float(value)
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
I wondered if there could be a test which would verify that original error traceback would be available?

**Comment by kyleam** [comment]
> I wondered if there could be a test which would verify that original error traceback would be available?

IMO it's not worth testing.

**Comment by kyleam** [comment]
> that original error traceback would be available?

It won't be available in Python 2 using this PR.  For example,

```python
import traceback

from pyout import Tabular
from pyout.field import StyleFunctionError
from humanize import naturalsize

out = Tabular(columns=["name", "size"],
              style={"size": {"transform": naturalsize}})

try:
    out({"name": "y", "size": "err"})
except StyleFunctionError as e:
    raise e
```

prints

```
Traceback (most recent call last):
  File "transform_error_gobble.py", line 14, in <module>
    raise e
pyout.field.StyleFunctionError: ValueError
  could not convert string to float: err
```

So, we end up with an informative message but still no traceback.  Do
you know a way preserve the traceback even in this case (aside from
just dumping it into StyleFunctionError's message)?

**Comment by kyleam** [comment]
I pushed a simple test case for the py2 case that this PR does fix.
The py2/py3 discrepancy I mention in my last comment is still present,
though.

**Comment by yarikoptic** [comment]
Well, my main point is giving enough information to the developer/user so he/she could figure out which field/value caused the trouble. So it would be ok for me if the reraised exception message in addition to the raised/caught exception message included %r of the function (even though it might often be a boring lambda without name) and the value (result) on which it pucked. That should be sufficient information for the user in the majority of cases to right away figure out a possible culprit. Original traceback, or at least location (file/line number, like we do in datalad with exc_str) might be useful for us to troubleshoot.

**Comment by kyleam** [comment]
So, your direct answer to

> Do you know a way to preserve the traceback even in this case (aside from just dumping it into StyleFunctionError's message)?

is "no"?

**Comment by yarikoptic** [comment]
yes, the answer was "no" -- couldn't remember anything like that.

**Comment by kyleam** [comment]
> yes, the answer was "no" -- couldn't remember anything like that.

OK, thanks.

To bring this back to datalad: if I make the following change on top
of your enh-pyout branch in order to trigger an error,

```diff
diff --git a/datalad/interface/ls.py b/datalad/interface/ls.py
index 5d38dc49..2def4e0e 100644
--- a/datalad/interface/ls.py
+++ b/datalad/interface/ls.py
@@ -557,7 +557,7 @@ def summary_dates(values):
                     #summary=lambda x: "TOTAL: %d" % len(x)
                 )),
                 ('type', dict(
-                    transform=lambda s: "[%s]" % s,
+                    transform=humanize.naturalsize,
                     #summary=summary_counts
                 )),
                 ('describe', dict(
```

here's the error that's displayed (under py2 and py3)

```
[ERROR  ] <function naturalsize at 0x7f58bac012f0> raised ValueError
|   could not convert string to float: 'git' [filesize.py:naturalsize:25] (StyleFunctionError)
```

So, the one line that `exc_str` takes from the traceback points to the
humanize naturalsize line rather than the location we
StyleFunctionError was raised.  So 330bd96 works correctly with
datalad's exception handling, at least.

And were the file/line number not displayed correctly, the message of
course still has the original error, the original message, and
(restored as of fca48e8) the name of the function

Before this PR, it showed your beloved

```
[ERROR  ] Style transform <function naturalsize at 0x7f7bb2ca12f0> raised an exception. See above. [field.py:transform_fn:268] (StyleFunctionError)
```

So, AFAICS, we're in OK shape.

**Comment by yarikoptic** [comment]
Looks good to me

**Comment by kyleam** [comment]
OK, I've squashed these and merged, since I think it's definitely an
improvement.  We can tweak later if needed.

**Pull request merged**
